# Site settings
# in the templates available like {{ site.myvariable }}.
title: Turmalina Negra
email: turmalinanegra@gmail.com
brand: Turmalina Negra
headline: Roupas feitas com Amor
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://turmalinanegra.github.io" # the base hostname & protocol for your site
copyright: Feito com Amor.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: turmalinanegra61@gmail.com
phone: +55-11-997328963

# Tracking
googleAnalitycsID: UA-83933844-1
