# Site settings
# in the templates available like {{ site.myvariable }}.
title: Turmalina Negra
email: turmalinanegra61@gmail.com
brand: Turmalina Negra
headline: Roupas
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://turmalinanegra.github.io" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: turmalinanegra61@gmail.com
phone: +1-800-555-2016

# Tracking
googleAnalitycsID: UA-83933844-1

