# Site settings
# in the templates available like {{ site.myvariable }}.
title: Turmalina Negra
email: turmalinanegra@gmail.com
brand: Turmalina Negra
headline: Moda Energética
description: > # this means to ignore newlines until "baseurl:"
  Moda Energética
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://turmalinanegra.github.io" # the base hostname & protocol for your site
copyright: Site feito com ♥

# Build settings
markdown: kramdown

# Account ids
snapwidget: 592173

# Contacts
email: turmalinanegra61@gmail.com
phone: (15)88066489

# Tracking
googleAnalitycsID: UA-83933844-1
